apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: local
spec:
  # menamai StorageClass dengan 'hostpath'
  storageClassName: hostpath
  # Filesystem: pv digunakan sebagai sistem berkas
  volumeMode: Filesystem
  # kapasitas storage 1000MB
  capacity:
    storage: 1000Mi
  # hanya satu node yang dapat membaca dan menulis pada satu waktu
  accessModes:
    - ReadWriteOnce
  # "Retain" berarti data PersistentVolume akan tetap ada setelah claim dihapus
  persistentVolumeReclaimPolicy: Retain
  # jalur host sistem file yang digunakan oleh pv
  hostPath:
    path: "/tmp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
      