apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # MONGO_ROOT_USERNAME dengan admin dan 
  # MONGO_ROOT_PASSWORD dengan supersecretpassword dalam bentuk base64
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
