apiVersion: v1
kind: Service
metadata:
  # service name for karsajobs-ui
  name: karsajobs-ui
  labels:
    app: karsajobs
spec:
  # use NodePort for service type, agar daapt diakses di luar cluster
  type: NodePort
  selector:
    app: karsajobs
    tier: frontend
  ports:
  - port: 8000
    # By default and for convenience, the `targetPort` is set to
    # the same value as the `port` field.
    targetPort: 8000
    # Optional field
    # By default and for convenience, the Kubernetes control plane
    # will allocate a port from a range (default: 30000-32767)
    nodePort: 30007
  